require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ShopCustomersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ShopCustomer. As you add validations to ShopCustomer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShopCustomersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all shop_customers as @shop_customers" do
      shop_customer = ShopCustomer.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:shop_customers)).to eq([shop_customer])
    end
  end

  describe "GET #show" do
    it "assigns the requested shop_customer as @shop_customer" do
      shop_customer = ShopCustomer.create! valid_attributes
      get :show, {:id => shop_customer.to_param}, valid_session
      expect(assigns(:shop_customer)).to eq(shop_customer)
    end
  end

  describe "GET #new" do
    it "assigns a new shop_customer as @shop_customer" do
      get :new, {}, valid_session
      expect(assigns(:shop_customer)).to be_a_new(ShopCustomer)
    end
  end

  describe "GET #edit" do
    it "assigns the requested shop_customer as @shop_customer" do
      shop_customer = ShopCustomer.create! valid_attributes
      get :edit, {:id => shop_customer.to_param}, valid_session
      expect(assigns(:shop_customer)).to eq(shop_customer)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ShopCustomer" do
        expect {
          post :create, {:shop_customer => valid_attributes}, valid_session
        }.to change(ShopCustomer, :count).by(1)
      end

      it "assigns a newly created shop_customer as @shop_customer" do
        post :create, {:shop_customer => valid_attributes}, valid_session
        expect(assigns(:shop_customer)).to be_a(ShopCustomer)
        expect(assigns(:shop_customer)).to be_persisted
      end

      it "redirects to the created shop_customer" do
        post :create, {:shop_customer => valid_attributes}, valid_session
        expect(response).to redirect_to(ShopCustomer.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved shop_customer as @shop_customer" do
        post :create, {:shop_customer => invalid_attributes}, valid_session
        expect(assigns(:shop_customer)).to be_a_new(ShopCustomer)
      end

      it "re-renders the 'new' template" do
        post :create, {:shop_customer => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shop_customer" do
        shop_customer = ShopCustomer.create! valid_attributes
        put :update, {:id => shop_customer.to_param, :shop_customer => new_attributes}, valid_session
        shop_customer.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested shop_customer as @shop_customer" do
        shop_customer = ShopCustomer.create! valid_attributes
        put :update, {:id => shop_customer.to_param, :shop_customer => valid_attributes}, valid_session
        expect(assigns(:shop_customer)).to eq(shop_customer)
      end

      it "redirects to the shop_customer" do
        shop_customer = ShopCustomer.create! valid_attributes
        put :update, {:id => shop_customer.to_param, :shop_customer => valid_attributes}, valid_session
        expect(response).to redirect_to(shop_customer)
      end
    end

    context "with invalid params" do
      it "assigns the shop_customer as @shop_customer" do
        shop_customer = ShopCustomer.create! valid_attributes
        put :update, {:id => shop_customer.to_param, :shop_customer => invalid_attributes}, valid_session
        expect(assigns(:shop_customer)).to eq(shop_customer)
      end

      it "re-renders the 'edit' template" do
        shop_customer = ShopCustomer.create! valid_attributes
        put :update, {:id => shop_customer.to_param, :shop_customer => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested shop_customer" do
      shop_customer = ShopCustomer.create! valid_attributes
      expect {
        delete :destroy, {:id => shop_customer.to_param}, valid_session
      }.to change(ShopCustomer, :count).by(-1)
    end

    it "redirects to the shop_customers list" do
      shop_customer = ShopCustomer.create! valid_attributes
      delete :destroy, {:id => shop_customer.to_param}, valid_session
      expect(response).to redirect_to(shop_customers_url)
    end
  end

end
